[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/cli"

[[constraint]]
  name = "github.com/moorara/goto"
  version = "0.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
