[root]
  country = ["CA", "US"]
  province = ["Ontario", "Massachusetts"]
  locality = ["Ottawa", "Boston"]
  organization = ["Moorara"]

[intermediate]
  country = ["CA"]
  province = ["Ontario"]
  locality = ["Ottawa"]
  organization = ["Moorara"]

[server]
  country = ["US"]
  province = ["Virginia"]
  locality = ["Richmond"]
  organization = ["Moorara"]

[client]
  country = ["UK"]
  locality = ["London"]
  organization = ["Moorara"]

[root_policy]
  match = ["Country", "Organization"]
  supplied = ["CommonName"]

[intermediate_policy]
  match = ["Organization"]
  supplied = ["CommonName"]

[metadata]
  ClientSkip = ["StreetAddress", "PostalCode"]
  IntermSkip = ["IPAddress", "StreetAddress", "PostalCode"]
  RootSkip = ["IPAddress", "StreetAddress", "PostalCode"]
  ServerSkip = ["StreetAddress", "PostalCode"]
