[root]
  country = [ "CA", "US" ]
  province = [ "Ontario", "Massachusetts" ]
  locality = [ "Ottawa", "Boston" ]
  organization = [ "Moorara" ]
[intermediate]
  country = [ "CA" ]
  province = [ "Ontario" ]
  locality = [ "Ottawa" ]
  organization = [ "Moorara" ]
  email_address = [ "moorara@example.com" ]
[root_policy]
  supplied = ["CommonName"]
[intermediate_policy]
  supplied = ["CommonName"]
