name: Main
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: moorara/checkout@fix-git-config-issue
        with:
          fetch-depth: o
      - name: Lint
        uses: gardenbed/actions/go-lint@main
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        id: test
        uses: gardenbed/actions/go-cover@main
        with:
          codeclimate_reporter_id: ${{ secrets.CODECLIMATE_REPORTER_ID }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ steps.test.outputs.coverage_report_file }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Build Binary
        run: go build .
