name: Go
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: gardenbed/actions/go-lint@main
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        id: test
        uses: gardenbed/actions/go-cover@main
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ${{ steps.test.outputs.coverage_report_file }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build Binary
        run: go build .
