name: Main
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Lint
        uses: moorara/actions/go-lint@master
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        id: test
        uses: moorara/actions/go-cover@master
        with:
          codeclimate_reporter_id: ${{ secrets.CODECLIMATE_REPORTER_ID }}
      - name: Upload Test Report
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: ${{ steps.test.outputs.coverage_report_file }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: moorara/actions/semver@master
        with:
          file: ./version/VERSION
      - name: Build
        uses: moorara/actions/cherry@master
        with:
          args: build -cross-compile=false
